### ISSUE TITLE
modify code 

### ISSUE THREAD

**Issue by mukund26** [mukund26/Reconnaince_scan#2]
code is applicable for changes for better and optimized working
change Reconnaince_scan.py for storing all results in one single file

**Comment by realazizk** [comment]
Please specify exactly what can be done.

**Comment by mukund26** [comment]
if code made one file rather than multiple files for output  @mohamed-aziz

**Comment by realazizk** [comment]
I think it would be better to open individual issues for each improvement you think of @mukund26

**Comment by mukund26** [comment]
i just want the reconnaince_scan.py to store result in one file @mohamed-aziz 
issues are not multiple

**Comment by n8urton** [comment]
should this issue be closed?
